### PR TITLE
Add full Portuguese-BR translation

### PR DESCRIPTION
**Pull request by MatheusTGamerPro**
Add the full translation into Portuguese Brazil at

```
values-pt-rBR/strings.xml
```

### CODE REVIEW

**Review by LegacyGamerHD — APPROVED** [review]
looks alright

**Comment by Tungstend** [comment]
Thx, have u test it, btw, can u also translate this.
https://github.com/Tungstend/HMCL-PE/blob/main/FilePicker/src/main/res/values-en/strings.xml

**Comment by MatheusTGamerPro** [comment]
> Thx, você testá-lo, btw, você também pode traduzir isso. https://github.com/Tungstend/HMCL-PE/blob/main/FilePicker/src/main/res/values-en/strings.xml

I am going yes.

**Comment by MatheusTGamerPro** [comment]
@Tungstend ready, FilePicker was also translated. if you are going to add my name in the translation contribution, add my first name "MatheusTGP" and not "MatheusTGamerPro", thank you.

**Pull request merged**
